NewBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from complaint import views as vw2
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"),
    path('about/', views.about,name = "about"),
    path('detail/<int:id>', views.detail),
    
    path('user/', include("user.urls")),
    path('articles/', include("article.urls")),
    path('complaint/', include("complaint.urls")),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views





app_name = "article"

urlpatterns = [

    path('create/',views.index),
    path('dashboard/', views.dashboard,name = "dashboard"),
    path('addarticle/', views.addarticle,name = "addarticle"),
    path('article/<int:id>/',views.detail,name ="detail" ),
    path('update/<int:id>/',views.updateArticle,name ="update" ),
    path('delete/<int:id>/',views.deleteArticle,name ="delete" ),
    path('',views.articles,name ="articles" ),
    path('comment/<int:id>/',views.addComment,name ="comment" ),

]

complaint/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "complaint"

urlpatterns = [

    path('addcomplaint/',views.addcomplaint,name = "add_complaint"),
    
    

]

user/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "user"

urlpatterns = [

    path('register/',views.registerUser,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout")
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Salih Arkanöz Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        
        {% if request.user.is_authenticated %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'complaint:add_complaint'%}">Şikayet & Öneri <span class="sr-only">(current)</span></a>
          </li>                       
        
        {% else %}
        {% endif %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:articles'%}">Makaleler <span class="sr-only">(current)</span></a>
          </li>

        
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about'%}">Hakkımda <span class="sr-only">(current)</span></a>
          </li>

          
      </ul>
      <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
                    <li class="nav-item active">
                  <a class="nav-link" href="{% url 'article:dashboard'%}">Kontrol Paneli <span class="sr-only">(current)</span></a>
                    
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'user:logout'%}">Çıkış Yap <span class="sr-only">(current)</span></a>
                </li>
          {% else %}
                      <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:register'%}">Kayıt Ol <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:login'%}">Giriş Yap <span class="sr-only">(current)</span></a>
              </li>
          {% endif %}
        
        

        
      </ul>
      

    </div>
</nav>