NewBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from complaint import views as vw2
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"),
    path('about/', views.about,name = "about"),
    path('detail/<int:id>', views.detail),
    
    path('user/', include("user.urls")),
    path('articles/', include("article.urls")),
    path('complaint/', include("complaint.urls")),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views





app_name = "article"

urlpatterns = [

    path('create/',views.index),
    path('dashboard/', views.dashboard,name = "dashboard"),
    path('addarticle/', views.addarticle,name = "addarticle"),
    path('article/<int:id>/',views.detail,name ="detail" ),
    path('update/<int:id>/',views.updateArticle,name ="update" ),
    path('delete/<int:id>/',views.deleteArticle,name ="delete" ),
    path('',views.articles,name ="articles" ),
    path('comment/<int:id>/',views.addComment,name ="comment" ),

]

complaint/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "complaint"

urlpatterns = [

    path('addcomplaint/',views.addcomplaint,name = "add_complaint"),
    
    

]

user/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "user"

urlpatterns = [

    path('register/',views.registerUser,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout")
]

article/models.py
from django.db import models
from ckeditor.fields import  RichTextField
# Create your models here.
class Article(models.Model):
    author  = models.ForeignKey("auth.User",on_delete= models.CASCADE,verbose_name="YAZAR")
    title = models.CharField(max_length=50,verbose_name="BAŞLIK")
    content = RichTextField(verbose_name="İÇERİK")
    created_date = models.DateTimeField(auto_now_add= True,verbose_name="OLUŞTURMA TARİHİ")
    article_image = models.FileField(blank=True,null=True,verbose_name="Görsel Ekleyin")
    def __str__ (self):
        return self.title
        
    class Meta:
        ordering = ["-created_date"]



class Comment(models.Model):
    article         = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Makale",related_name="comments")
    comment_author  = models.CharField(max_length=60,verbose_name="Yorum Sahibi")
    comment_content = RichTextField(verbose_name="Yorum")
    comment_date    = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ["-comment_date"]

complaint/models.py
from django.db import models
from ckeditor.fields import  RichTextField
# Create your models here.

# Create your models here.
class Complaint(models.Model):
    author  = models.ForeignKey("auth.User",on_delete= models.CASCADE,verbose_name="YAZAR")
    title = models.CharField(max_length=100,verbose_name="BAŞLIK")
    content = RichTextField(verbose_name="ŞİKAYET & ÖNERİ")
    created_date = models.DateTimeField(auto_now_add= True,verbose_name="OLUŞTURMA TARİHİ")

    def __str__ (self):
        return self.title

article/forms.py
from django import forms
from .models import Article
class Articleform(forms.ModelForm):
    class Meta:
        model  = Article
        fields = ["title","content","article_image"]

complaint/forms.py
from django import forms
from .models import Complaint
class Complaintform(forms.ModelForm):
    class Meta:
        model  = Complaint
        fields = ["title","content"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import Articleform
from django.contrib import messages
from.models import Article,Comment
from django.contrib.auth.decorators import login_required
# Create your views here.

def articles(request):

    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        context  = {"articles":articles}
        return render(request,"articles.html",context)



    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})


def index (request):
    articles = Article.objects.all()
    return render(request,"index.html",{"articles":articles})
    #return render (request,"index.html")



def about(request):
    return render (request,"about.html")



def detail(request,id):
    
    article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id=id)
    
    comments= article.comments.all()
    context = {"article":article,"comments":comments}

    return render(request,"detail.html",context)





@login_required
def dashboard (request):
    articles = Article.objects.filter(author = request.user)
    context = {"articles" : articles}
    return render(request,"dashboard.html",context)




@login_required
def addarticle(request):
    form = Articleform(request.POST or None,request.FILES or None)
    content = {"form":form}
    if request.method == "POST":
        if form.is_valid():
            article = form.save(commit=False)
            article.author =request.user
            article.save()

            messages.success(request,"Başarılı Şekilde Makaleniz Oluşturuldu")
            return redirect("article:dashboard")
        else:
            messages.warning(request,"BİR ŞEYLER TERS GİTİİ ):")
            return render(request,"addarticle.html",content)
    else:
        
        return render(request,"addarticle.html",content)

@login_required
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form    = Articleform(request.POST or None,request.FILES or None,instance=article)
    content = {"form":form}
    if form.is_valid():
        article = form.save(commit=False)
        article.author =request.user
        article.save()

        messages.success(request,"Başarılı Şekilde Makaleniz Güncellendi ve Kaydedildi.")
        return redirect("article:dashboard")

    return render(request,"update.html",content)

@login_required
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    article.delete()
    messages.success(request,"Makale Başarıyla Silindi.")
    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id = id)
    
    if request.method == "POST":
        comment_author  = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment          = Comment(comment_author=comment_author,comment_content=comment_content)
        newComment.article  = article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

complaint/views.py
from django.shortcuts import render,redirect,HttpResponse
from .forms import Complaintform
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def addcomplaint(request):
    form = Complaintform(request.POST or None)
    content = {"form":form}
    if request.method == "POST":
        if form.is_valid():
            article = form.save(commit=False)
            article.author =request.user
            article.save()

            messages.success(request,"Başarılı Şekilde Şikayetiniz & Öneriniz Kaydedildi")
            return redirect("index")
    return render (request,"complaint.html",content)
    

templates/about.html
{% extends "layout.html" %}

{% block body %}
 

<div class = "col-md-6 offset-md-3"></div>
<h1 class = "text-center">HAKKIMDA</h1>
        <hr>
    <div class = "jumbotron text-center">
    
        
        <p>Merhaba öğrenmeyi felsefe haline getirmiş güzel insanlar ! Bu sayfada bol bol farklı konular üzerine okumuş veya kafa yormuş insanların yazıları ile internetteki blog kültürüne olan vefa borcumuzu ödemeyi planlıyoruz!</p>
        <br>
        <br>
        <br>
        <img  class="rounded" src="https://ozuburs.ozyegin.edu.tr/sites/ozuburs.ozyegin.edu.tr/files/salih-metin.png" />
        <br>
        <br>
        <h3>Merhaba Herkese ! Adım Salih , Bilgisayar Mühendisliği Hazırlık öğrencisiyim :) </h3>
        <p>Bu blog sayfasını kodlamamın sebebi , sanal ortamda varlığımı yaratmaktan ziyade insanlarla sürekli bilgi alışverişinde olmak diyebiliriz.

        </p>
        <p>Ancak bir sebebi daha var ? Üretmek !...</p>
        <p>Üretmenin bilincinde yaşamak adına bir şeyleri üretip kullanmak ve kullanıma sunmak oldukça keyifli gelmeye başlamıştı.</p>
        <p>Ailem için yazdığım bir Bütçe Programında bunu anlamıştım</p>
        <p>dilerim ki bu sayfaya davet ettiğim editörlerle birlikte güzel bir paylaşım merkezi haline gelir bu adres.</p>
        <p>HER ZAMAN AMA HER ZAMAN ELEŞTİRİ & ÖNERİ & ŞİKAYETE AÇIK OLARAK SİZLERİN GERİ DÖNÜŞLERİNİ BEKLİYOR OLACAĞIM</p>
        <p>Herkese keyifli öğrenmeler diliyorum, BİLİM ve SAĞLIKLA kalınız efendim...</p>
    </div>
</div>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% load crispy_forms_tags  %}
{% block body %}

<div class = "col-md-15 offset-md-1">
<h3 class = "text-center">Makale Ekle</h3>
<hr>




                <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form.media}}
                            {{form|crispy}}
                            <button type ="submit" class="btn btn-primary">Makale Oluştur</button>
                </form>
        
        





</div>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}


{% block body %}

        

<h1>Makaleler</h1>


{% if articles %}
<form class="form-inline mr-auto">
{% csrf_token %}
  <input class="form-control mr-sm-2" name ="keyword" type="text" style="width: 300px; height: 40px;" placeholder="Ne Aramıştınız?" aria-label="Search">
  <button class="btn btn-outline-primary btn-rounded btn-sm my-5" style="width: 80px; height: 40px" type="submit">Ara</button>
</form>

{% for article in articles  %}
<div class="row">

      <!-- Post Content Column -->
    <div class="col-lg-11">

        <!-- Title -->
        <h2 class="mt-4" ><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></h2>
                                  
        <!-- Author -->
        <p class="lead">
          
          {{article.author}} tarafından {{article.created_date}} tarihinde yayınlandı.
        </p>

          

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        
        <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded"  src="{{article.article_image.url}}" alt=""></a>
        {% endif %}
        

        <hr>

         
        <p class="lead">{{article.content|safe|truncatewords:40}} </p>
        <hr>
        <a style="float:  right " class="btn btn-primary" href="{% url 'article:detail' article.id %}">Devamını Oku</a>
        
 
        

    </div>
</div>
{% endfor %}






{% else %}
<div class="row">

      <!-- Post Content Column -->
    <div class="col-lg-7">
<div class = "alert alert-danger">
        MAKALE BULUNAMADI  :(
</div>
</div>
</div>
{% endif %}


{% endblock body %}

templates/complaint.html
{% extends "layout.html" %}

{% block body %}
<h2>Şikayet ve Önerilerinizi ÖNEMSİYORUZ</h2>
<hr>
    <div class = "jumbotron text-center">
            <form method="post">
                
                {% csrf_token %}
                {{form.media}}
                
                {{form.as_p}}
                <button type=submit class = "btn btn-danger">GÖNDER</button>

    </form>
    
    
    </div>
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}


{% block body %}
<div class = "col-md-8 offset-md-2" >
<h3>Kontrol Paneli</h3>
<hr>
<h5>Hoşgeldiniz {{request.user.username}}</h5>
<hr>

<a class= "btn btn-danger"href="{% url 'article:addarticle' %}">Yeni Makale Ekle</a>
<br>
<br>
{% if articles %}
<table class="table">
            <thead class="thead-dark">
                <tr>
                
                <th scope="col">Başlık</th>
                <th scope="col">Yazar</th>
                <th scope="col">Tarih</th>
                <th scope="col">Güncelle</th>
                <th scope="col">Sil</th>
                </tr>
            </thead>
            <tbody>
                {% for article in articles  %}
                        
                
                    <tr>
                    
                    <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
                    <td>{{article.author}}</td>
                    <td>{{article.created_date}}</td>
                    <td><a href="{% url 'article:update' article.id %}" class="btn btn-primary">Güncelle</a></td>
                    <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
                    </tr>
                {% endfor %}
            </tbody>
</table>
{% else %}
<div class = "alert alert-danger">Gösterilecek Bir Makaleniz Yok, Ama Hemen Yukarıdan YENİ MAKALE Ekleyebilirsiniz.</div>

{% endif %}

</div>
{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{article.title}}</h1>

        <!-- Author -->
        <p class="lead">
          {{article.author}} tarafından {{article.created_date}} tarihinde yayınlandı.
        </p>

        

        <!-- Date/Time -->
        

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        
        {% endif %}
        

        <hr>
        

        <!-- Post Content -->
        <p class="lead">{{article.content|safe}} </p>
        <blockquote class="blockquote">
        <!-- Post Comments -->

            {% if comments %}
                  
                  <h4>Yorumlar</h4>
                  <hr>
                      {% for comment in comments  %}
                          <div class="media mb-4">
                                  
                                  <img class="d-flex mr-3 rounded-circle" src="https://muratselek.com.tr/wp-content/uploads/2019/01/yorum-icon-avatar-men-50x50.png" alt=""> 
                                    <div class="media-body">
                                      <h6 class="mt-0" style="font-weight:bold;">{{comment.comment_author}} , {{comment.comment_date}} :</h6>
                                        
                                      {{comment.comment_content|safe}}
                                    </div>
                          </div>
                      {% endfor %}
                    
            {% else %}
              <hr>
              <div class = "alert alert-danger">Henüz hiç yorum yok, İlk yorum yapan hemen siz olun! </div>
            {% endif %}










          <div class="card my-4">
                  
            <h5 class="card-header">Yorum Ekle:</h5>
            <div class="card-body">
                    
              <form method = "post" action = "{% url 'article:comment' article.id%}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Yorum Sahibi</label>
                        <input name ="comment_author" type="text" class="form-control" id="exampleInputEmail1"  placeholder="İsminiz...">
                    </div>
                    <label for="comment">Yorum </label>
                <div class="form-group">
                  <textarea name ="comment_content" class="form-control" rows="3" placeholder="Yorumunuz..."></textarea>
                </div>
                
                <button style="float:right ; width: 100px; height: 40px;" type="submit" class="btn btn-primary">Ekle</button>
              </form>
            </div>
          </div>
          <!-- Post Comments End -->
        <hr>
      </div>
        

    </div>
    <!-- /.row -->
{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class = "jumbotron text-center">

    <header class="masthead text-white text-center">
        
        <div class="overlay"></div>
        <div class="container" >
            <h1 style="color: rgb(32, 28, 28);"> Blog Sayfama Hoşgeldiniz !</h1>
          <div class="row">
            <div class="col-xl-9 mx-auto" >
                {% if request.user.is_authenticated %}
                   
                {% else %}
                    <h1 class="mb-5" style="color: rgb(32, 28, 28);">...Hemen Katıl , Yeter ki PAYLAŞ...</h1>
                    <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
                        <form>
                          <div class="form-row">
                            
                            <div class="col-12 col-md-14">
                              <button type="submit" formaction="{% url 'user:register'%}" class="btn btn-block btn-lg btn-primary"> <a style="color: rgb(255, 255, 255); ;">HEMEN KAYIT OL</a></button>
                                <br>
                                <br>
                              <div class = "alert alert-warning">
                                 HENÜZ KAYITLI DEĞİLSİNİZ ya da GİRİŞ YAPMADINIZ :(
                        </div>
                            </div>
                          </div>
                        </form>
                      </div>
                    

                {% endif %}
              
            </div>
            
          </div>
        </div>
      </header>

        
        <!-- > <p>MERHABA ARKADAŞLAR , SAYFAMIZ YAPIM AŞAMASINDADIR !</p> -->

       
    
    


<p>
    <br>
    <br>
    



</p>
</div>
<h1>Makaleler</h1>


{% if articles %}
<form class="form-inline mr-auto">
<!--{% csrf_token %}
  <input class="form-control mr-sm-2" name ="keyword" type="text" style="width: 300px; height: 40px;" placeholder="Ne Aramıştınız?" aria-label="Search">
  <button class="btn btn-outline-primary btn-rounded btn-sm my-5" style="width: 80px; height: 40px" type="submit">Ara</button>
</form> -->

{% for article in articles  %}
<div class="row">

      <!-- Post Content Column -->
    <div class="col-lg-11">

        <!-- Title -->
        <h2 class="mt-4" ><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></h2>
                                  
        <!-- Author -->
        <p class="lead">
          
          {{article.author}} tarafından {{article.created_date}} tarihinde yayınlandı.
        </p>

          

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        
        <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded"  src="{{article.article_image.url}}" alt=""></a>
        {% endif %}
        

        <hr>

         
        <p class="lead">{{article.content|safe|truncatewords:75}} </p>
        <hr>
        <a style="float:  right " class="btn btn-primary" href="{% url 'article:detail' article.id %}">Devamını Oku</a>
        
 
        

    </div>
</div>
{% endfor %}






{% else %}
<div class="row">

      <!-- Post Content Column -->
    <div class="col-lg-7">
<div class = "alert alert-danger">
        MAKALE BULUNAMADI  :(
</div>
</div>
</div>
{% endif %}

{% endblock body %}

templates/layout.html
{%load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block head %}
    
    {% endblock head %}
    <title>Blog</title>
</head>
<body>
    {% include "includes/navbar.html" %}
    <br>
        
    <br>
    
    <div style ="margin-top: 75px; margin-bottom: 130px;"class = "container">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
            </ul>
            {% endfor %}
            
            {% endif %}
    
            
        {% block body %}
        
        {% endblock body %}
    </div>
    <script src='{% static "js/jquery-3.2.1.min.js" %}'></script>
    <script src='{% static "js/bootstrap.min.js" %}'></script>
    
    </body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags  %}



<div class = "col-md-6 offset-md-3">
<h3>GİRİŞ YAP</h3>

<hr>
<div class = "jumbotron text-center">



                <form method="post">
                            {% csrf_token %}
                            {{form|crispy}}
                            <button type ="submit" class="btn btn-primary">Giriş Yap</button>
                </form>
        
        </div>




</div>


        

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags  %}
<div class = "col-md-6 offset-md-3">

<h3>KAYIT OL</h3>

<hr>

        <div class = "jumbotron text-center">



                <form method="post">
                            {% csrf_token %}
                            {{form|crispy}}
                            <button type ="submit" class="btn btn-primary">Kayıt Ol</button>
                </form>
        
        </div>

</div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% load crispy_forms_tags  %}
{% block body %}

<div class = "col-md-15 offset-md-1">
<h3 class = "text-center">Makale Güncelle</h3>
<hr>




                <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form.media}}
                            {{form|crispy}}
                            <button type ="submit" class="btn btn-primary">Makaleyi Kaydet</button>
                </form>
        
</div>
{% endblock body %}